name: Manuell Benchmark

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
    add-runner:
      uses: ./.github/workflows/runner_attach_workflow.yml
      with:
        RunnerCount: 1
        RunnerComputeType: "M"
      secrets:
        GitHubToken: ${{ secrets.RUNNER_ATTACH_API_KEY }}
        AWSRoleToAssume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

    benchmark-test:
      needs: add-runner
      runs-on: self-hosted
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - uses: actions/setup-python@v5
          id: setup-python
          with:
            python-version: '3.10'
        - name: Benchmark
          run: |
            pip install '.[dev]'
            python -m benchmark