name: Run Benchmark

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:


  benchmark-test:
    needs: add-runner
    runs-on: self-hosted
    env:
      BAYBE_BENCHMARKING_PERSISTENCE_PATH: ${{ secrets.TEST_RESULT_S3_BUCKET }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: "3.10"
      - name: Benchmark
        run: |
          pip install '.[benchmarking]'
          python -m benchmarks
