name: Manuell Performance Tests
on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
    add-runner:
      uses: ./.github/workflow_templates/runner_attach_workflow.yml
      with:
        RunnerCount: 1
        RunnerComputeType: "M"
      secrets:
        GitHubToken: ${{ secrets.RUNNER_ATTACH_API_KEY }}
        AWSRoleToAssume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

    performancetest:
      needs: add-runner
      runs-on: self-hosted
      name: Performance Tests 3.10
      env:
        BAYBE_PERFORMANCE_TEST_RESULT_S3_BUCKET_NAME: ${{ secrets.TEST_RESULT_S3_BUCKET }}
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - uses: actions/setup-python@v5
          id: setup-python
          with:
            python-version: '3.10'
        - name: Run performance test
          run: |
            pip install tox-uv
            tox -e performancetest-py310